#!/bin/bash

###################
### DESCRIPTION ###
###################

# Use this script after installing Arch Linux with archinstall

#############
### NOTES ###
#############

# Testing needed.
# Repositories need to be public

#################
### VARIABLES ###
#################

pacinstall="sudo pacman -S --needed --noconfirm"

###########
### SSH ###
###########

$pacinstall openssh
ssh-keygen -f $HOME/.ssh/id_ed25519
echo "Please enter <user>@<hostname> to share your public key with an SSH server:"
read sshServer
ssh-copy-id -i $HOME/.ssh/id_25519.pub $sshServer

###########
### YAY ###
###########

# Install yay and its dependencies
$pacinstall git base-devel
cd ~ || exit
git clone https://aur.archlinux.org/yay.git
cd yay || exit
makepkg -si
yay -Y --gendb
yay -Syu --devel
yay -Y --devel --save

#################
### CLI TOOLS ###
#################

$pacinstall bash-completion brightnessctl btop fastfetch git man-db nano openssh speedtest-cli tailscale
yay -S paccache-hook --noconfirm

# Run at shell startup. Add additional programs by appending \n<command> before the endquote.
echo -e "\n# Run at shell startup\nfastfetch" >> .bashrc

########################
### GUI APPLICATIONS ###
########################

$pacinstall alacritty firefox libreoffice-fresh mousepad qbittorrent steam vlc
yay betterbird-bin libation visual-studio-code.bin --noconfirm

# virt-manager
$pacinstall dmidecode dns-masq libvirt qemu-full swtpm virt-manager
sudo systemctl enable libvirtd.socket

# thunar
$pacinstall file-roller gvfs thunar thunar-archive-plugin thunar-volman

# nwg-look
$pacinstall adw-gtk-theme nwg-look

###############
### FLATPAK ###
###############
$pacinstall flatpak
#flatpak install -y com.github.tchx84.Flatseal com.heroicgameslauncher.hgl

######################
### NVIDIA DRIVERS ###
######################

$pacinstall nvidia-open nvidia-utils lib32-nvidia-utils nvidia-settings
# https://wiki.archlinux.org/title/NVIDIA#DRM_kernel_mode_setting 1.2.1 Early loading

###############
### LIGHTDM ###
###############
$pacinstall lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings xorg-server
sudo systemctl enable lightdm.service
cd /etc/ || exit
sudo git clone https://github.com/user241324/configs/tree/main/lightdm

###############
### WAYLAND ###
###############

# hyprland compositor
$pacinstall hyprland hyprpaper otf-font-awesome waybar wofi
cd ~/.config/
git clone https://github.com/user241324/configs/tree/main/hypr
git clone https://github.com/user241324/configs/tree/main/waybar

###########
### X11 ###
###########

# i3 window manager
$pacinstall feh i3-wm polybar rofi xorg
cd ~/.config/
git clone https://github.com/user241324/configs/tree/main/i3
git clone https://github.com/user241324/configs/tree/main/polybar
chmod +x /home/tom/.config/polybar/launch.sh

###################
### BACKGROUNDS ###
###################

cd /usr/share/
git clone https://github.com/user241324/backgrounds

##############
### REBOOT ###
##############

# Restart the system
sudo reboot now
