#!/bin/bash

#TESTING NEEDED
#NEED TO GENERATE AND ADD PAT (PERSONAL ACCESS TOKEN) FROM GITHUB AND TO GIT CLONE COMMANDS
##git clone https://username:<PAT>@github.com/user241324/<etc>
##OR MAKE THE REPOSITORIES PUBLIC

# Use this script after installing Arch Linux with archinstall

#################
### VARIABLES ###
#################

pacinstall = "sudo pacman -S --needed --noconfirm"

##############
### UPDATE ###
##############

sudo pacman -Syu --noconfirm

#################
### CLI TOOLS ###
#################

$pacinstall bash-completion brightnessctl btop fastfetch git man-db nano openssh speedtest-cli tailscale

########################
### GUI APPLICATIONS ###
########################

$pacinstall alacritty firefox libreoffice-fresh mousepad qbittorrent steam vlc

# virt-manager
$pacinstall dmidecode dns-masq libvirt qemu-full swtpm virt-manager
sudo systemctl enable libvirtd.socket

# thunar
$pacinstall file-roller gvfs thunar thunar-archive-plugin thunar-volman

# nwg-look
$pacinstall adw-gtk-theme nwg-look

###########
### YAY ###
###########

# Install yay and its dependencies
$pacinstall git base-devel
cd ~ || exit
git clone https://aur.archlinux.org/yay.git
cd yay || exit
makepkg -si
yay -Y --gendb
yay -Syu --devel
yay -Y --devel --save

# yay applications
yay betterbird-bin libation paccache-hook visual-studio-code.bin --noconfirm

###############
### FLATPAK ###
###############
$pacinstall flatpak
#flatpak install -y com.github.tchx84.Flatseal com.heroicgameslauncher.hgl

###############
### LIGHTDM ###
###############
$pacinstall lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings xorg-server
sudo systemctl enable lightdm.service
cd /etc/ || exit
sudo git clone https://github.com/user241324/configs/tree/main/lightdm

###############
### WAYLAND ###
###############

# hyprland compositor
$pacinstall hyprland hyprpaper otf-font-awesome waybar wofi
cd ~/.config/
git clone https://github.com/user241324/configs/tree/main/hypr
git clone https://github.com/user241324/configs/tree/main/waybar

###########
### X11 ###
###########

# i3 window manager
$pacinstall feh i3-wm polybar rofi xorg
cd ~/.config/
git clone https://github.com/user241324/configs/tree/main/i3
git clone https://github.com/user241324/configs/tree/main/polybar
chmod +x /home/tom/.config/polybar/launch.sh

###################
### BACKGROUNDS ###
###################

cd /usr/share/
git clone https://github.com/user241324/backgrounds

##############
### REBOOT ###
##############

# Restart the system
sudo reboot now
